// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrsPmEYexmiTgvD-O4zwZsdvUcnUYPNIQ',
    appId: '1:1008909438498:web:a608e894e4e70d73ebc47b',
    messagingSenderId: '1008909438498',
    projectId: 'ul-calender',
    authDomain: 'ul-calender.firebaseapp.com',
    storageBucket: 'ul-calender.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ9C0l9jhPSP1M423MfDLVY-rr-avEpy8',
    appId: '1:1008909438498:android:b036fdee6c6aa5b0ebc47b',
    messagingSenderId: '1008909438498',
    projectId: 'ul-calender',
    storageBucket: 'ul-calender.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoBhXHzUYuBL8mhbQAdeI5NADq2mS7MLk',
    appId: '1:1008909438498:ios:4d3ed89ce43dfd85ebc47b',
    messagingSenderId: '1008909438498',
    projectId: 'ul-calender',
    storageBucket: 'ul-calender.firebasestorage.app',
    iosBundleId: 'com.antigravity.oneUiCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoBhXHzUYuBL8mhbQAdeI5NADq2mS7MLk',
    appId: '1:1008909438498:ios:4d3ed89ce43dfd85ebc47b',
    messagingSenderId: '1008909438498',
    projectId: 'ul-calender',
    storageBucket: 'ul-calender.firebasestorage.app',
    iosBundleId: 'com.antigravity.oneUiCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrsPmEYexmiTgvD-O4zwZsdvUcnUYPNIQ',
    appId: '1:1008909438498:web:237a6c04b577cc0cebc47b',
    messagingSenderId: '1008909438498',
    projectId: 'ul-calender',
    authDomain: 'ul-calender.firebaseapp.com',
    storageBucket: 'ul-calender.firebasestorage.app',
  );
}
